// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutCompanion.Server.Data;

#nullable disable

namespace WorkoutCompanion.Server.Data.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    [Migration("20260916081350_StoreTimestampsAsUnixMilliseconds")]
    partial class StoreTimestampsAsUnixMilliseconds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.SessionExerciseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrescribedWeightCentiKgSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepMaxSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepMinSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultingProgressionDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultingProgressionTargetReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultingProgressionWeightCentiKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrderSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceProgressionTrackSyncId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetDurationSecondsSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProgressionTrackSyncId");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("WorkoutSessionId", "SortOrderSnapshot");

                    b.ToTable("SessionExercises", (string)null);
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.SessionSetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualWeightCentiKg")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CountsForProgression")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrescribedDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrescribedReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrescribedWeightCentiKg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SessionExerciseId", "SetOrder");

                    b.ToTable("SessionSets", (string)null);
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.WorkoutSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("StartedAt");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.ToTable("WorkoutSessions", (string)null);
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.SessionExerciseEntity", b =>
                {
                    b.HasOne("WorkoutCompanion.Server.Data.Entities.WorkoutSessionEntity", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.SessionSetEntity", b =>
                {
                    b.HasOne("WorkoutCompanion.Server.Data.Entities.SessionExerciseEntity", "SessionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("SessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.SessionExerciseEntity", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutCompanion.Server.Data.Entities.WorkoutSessionEntity", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
